
BASE = ../../rai

DEPEND = Core Algo Kin Gui Geo KOMO Optim 

SRCS = main.cpp
OBJS = main.o

GL = 1

CPATHS += /usr/include/eigen3
CPATHS += /usr/local/include/ompl-1.5
LIBS += -lompl 

include $(BASE)/build/generic.mk
